### PR TITLE
CI: change GitHub actions to separate build and test jobs

### PR DESCRIPTION
**Pull request by MSoegtropIMC**
Furthermore use make targets rather than opam files

This is work in progress.

### CODE REVIEW

**Comment by intoverflow** [comment]
Is it possible to do Build Phase using the opam files, then Test Phase using Make?

**Comment by MSoegtropIMC** [comment]
@intoverflow : one could probably do both with opam files, but @andrew-appel wanted to have more flexibility in this, so we agreed to switch to make targets.

**Comment by MSoegtropIMC** [comment]
@andrew-appel : this is ready for review. I enabled those tests which actually pass - but for performance reasons not in all build variants.

One interesting point: the "test" target runs 70 minutes on 32 bit and <15 minutes on 64 bit. I guess the tests do not the same in both cases. You might want to refactor this so that the extra things "test" does on 32 bit go into a separate target, so that one can more easily gather statistics over run time for 32 and 64 bit.

**Comment by andrew-appel** [comment]
Master-branch VST now has "test2" building correctly in 64-bit mode.
Now I'll merge this PR into master.

**Pull request merged**
