### PR TITLE
Try increasing the timeout for the build of Coq

### PR DESCRIPTION
**Pull request by maximedenes**
Please do not merge, in case CI succeeds, we will adjust the timeout to a more reasonable value.

### CODE REVIEW

**Comment by maximedenes** [comment]
@andrew-appel the coq build did terminate successfully, in about 11 minutes. So the timeout value was indeed the problem. I'll let the CI run to the end, then adjust it to 20 minutes.

**Comment by andrew-appel** [comment]
That step took 690 seconds, which is about 12 minutes; so therefore I'll put a 15-minute travis-wait in the script.

**Comment by maximedenes** [comment]
> so therefore I'll put a 15-minute travis-wait in the script.

I'm afraid this is going to be too tight sometimes. Build time can vary greatly from one run to another on these VMs. I'd put a timeout that is about 30 minutes, just to be sure. There's little change this step is going to start diverging anyway.

**Comment by maximedenes** [comment]
`travis_wait` has been added, so closing this.

**Pull request closed without merging**
