### PR TITLE
slightly change notations to prevent conflict with : of ssreflect

### PR DESCRIPTION
**Pull request by ildyria**
Proposed to solve: https://github.com/PrincetonUniversity/VST/issues/111

rename `:` by `<:` .

### CODE REVIEW

**Comment by ildyria** [comment]
Failed due to timeout (again).

**Comment by mansky1** [comment]
Hmm. I'm going to try reorganizing the Travis script.

**Comment by mansky1** [comment]
Could you merge master into your branch and then try again?

**Comment by andrew-appel** [comment]
I am very unhappy with this change.  Why should an "only printing" notation cause a conflict with some other package?  And why should ssreflect pollute my system and cause me to use an unnatural notation?

Thank you, ildyria, for identifying the problem and proposing this fix, but I would really like to discuss this with the Coq team.  Can you write a sentence or two that explains the situation?

**Pull request closed without merging**
