### PR TITLE
Adapt to https://github.com/coq/coq/pull/19530

### PR DESCRIPTION
**Pull request by proux01**
Adapt to https://github.com/coq/coq/pull/19530
This should be backward compatible and can be merged at your convenience, before the upstream PR.

### CODE REVIEW

**Comment by andrew-appel** [comment]
Can you merge the current master branch into this one, then commit and push (no need to build locally)?  The only change that you would be merging is an update of the CI script.

**Comment by proux01** [comment]
@andrew-appel rebased on master

**Comment by proux01** [comment]
Thanks

BTW, what's the status of VST master about compilation on CompCert master ?

**Comment by andrew-appel** [comment]
#781 brought VST up to date with compcert master as of 28 July 2024.  I'm not sure if there are incompatibilities since that date, but perhaps not.

**Comment by proux01** [comment]
Thanks, I didn't notice that, I'll try to update Coq CI to have VST there use CompCert master rather than recompiling the bundled one.

**Pull request merged**
