### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
(hopefully)

**Comment by andrew-appel** [comment]
Did we intend to use COMCPERT=bundled in VST's own CI?  I discussed the idea that Coq's CI for VST used "bundled", but I believe we intend that VST's own CI should get CompCert from opam.

**Comment by SkySkimmer** [comment]
compcert 3.10 doesn't have a opam package so not sure what the alternative is

**Comment by Zimmi48** [comment]
The remaining issue, which is specific to 8.14 and the 32bit version, seems like a real one:
```
  - File "./sha/general_lemmas.v", line 56, characters 34-53:
  Error: - Error: Found no subterm matching "?M3114 mod ?M3115" in the current goal.
```

As for getting CompCert 3.10 from opam, I'd rather defer it to @MSoegtropIMC to add the package, since he has done it in the past and best knows what to do.

**Comment by andrew-appel** [comment]
In other PRs, some of which are already in the master branch, we are fixing the CI in a different way.

**Pull request closed without merging**
