### PR TITLE
Change the setting of INSTALLDIR.

### PR DESCRIPTION
**Pull request by txyyss**
Set INSTALLDIR to the default one if ARCH is native.

### CODE REVIEW

**Comment by andrew-appel** [comment]
This looks good to me.  I suggest you put this comment into the Makefile at line 230:
```
#  1. (if present) the VST installation for reasoning about 64-bit-mode C programs on the host 
#         architecture will be in $(COQLIB)/user-contrib/VST, 
#  2. (if present) the VST installation for reasoning about 32-bit-mode C programs for the 32-bit analogue
#       of the host architecture will be in $(COQLIB)/../coq-variant/VST32/VST
#  3. (if present) a VST installation for reasoning about C programs compiled for a _different_ 
#        architecture will be in $(COQLIB)/../coq-variant/VST_otherarch_bitsize/VST
#  Not all of this logic is right here in this makefile; some of it is done in the CompCert install,
#  in choosing how to configure CompCert itself, creating the values of $(ARCH) and $(BITSIZE)
```

**Review by MSoegtropIMC — APPROVED** [review]
Looks good to me, but indeed I would add the comment suggested by Andrew.

**Comment by MSoegtropIMC** [comment]
Possibly one could change `IS_ARM` and `IS_X86` to `BOTH_ARM` and `BOTH_X86` since the logic is not that easy to understand.

**Comment by andrew-appel** [comment]
I will go ahead and make these changes now.

**Pull request merged**
