### PR TITLE
Split conclib into coqlib, sublist, veric, and concurrent parts

### PR DESCRIPTION
**Pull request by intoverflow**
# Summary of changes

cc @txyyss 

`concurrency/conclib.v` contains a mixture of concurrent and generic definitions and lemmas. In this PR we identify and relocate the generic parts.

We also update opam packages to reflect current versions. Lastly, we update the CI to support Coq 8.15 with compcert 3.10.

# conclib

conclib has been split into 4 parts:

* [coqlib](https://github.com/intoverflow/VST/blob/tcarstens/conclib/concurrency/conclib_coqlib.v)
* [sublist](https://github.com/intoverflow/VST/blob/tcarstens/conclib/concurrency/conclib_sublist.v)
* [veric](https://github.com/intoverflow/VST/blob/tcarstens/conclib/concurrency/conclib_veric.v)
* [concurrency](https://github.com/intoverflow/VST/blob/tcarstens/conclib/concurrency/conclib.v)

In this draft PR the files remain located in `concurrency/`.

It's apparent that the veric content should go in `veric/` and that the sublist content should go in `floyd/`, but I'm not sure where to stash the coqlib extensions. *Feedback/input is welcome.*

# opam packages

I updated the compcert version to 3.10. I also removed `sha-hmac` and `mailbox` from the 32-bit opam file. These examples do not seem to build right now, and I noticed they had already been removed from the 64-bit opam file.

# CI updates

compcert 3.9 requires Coq < 8.15. At least, that's what the published opam file for compcert 3.9 says.

Because of this, our CI cannot test VST 2.8 and prior on Coq 8.15.

So I went ahead and updated the CI:

1. The primary CI action (`coq-action.yml`) has been updated to test on Coq 8.13, 8.14, and 8.15. But it no longer tests our old releases.
2. To continue to support CI for our recent previous releases, I have created `coq-action-legacy.yml` which continues to test our 2.7 and 2.8 releases for Coq 8.13 and 8.14.

### CODE REVIEW

**Comment by mansky1** [comment]
Thank you so much for doing this! I have no special insight on where the `coqlib` stuff should go, but my instinct would be to put it as far down as possible (e.g. `msl/Coqlib2.v`).

**Comment by andrew-appel** [comment]
PR #542 (now merged into master) included some adjustments to the makefile:  vst,test,test2,test3,tests targets meant to be used for opam and CI.  This may be relevant to what you're doing here.  In particular, the VST opam build will use the "vst" target, and various tests that can be run in parallel will use test,test2,test3,etc.

**Comment by andrew-appel** [comment]
I'm working in this P.R. (merging master into it) today, so let's not duplicate work.

**Comment by andrew-appel** [comment]
@QinshiWang:  In working on this PR, I plan to move much of what is in concurrency/conclib_sublist.v into zlist/sublist.v.  This includes a lot of lemmas, but only one small Hint, so it should not disturb the list solver.  Let me know your opinion.

**Comment by txyyss** [comment]
I'm cloning and will test it once the clone is done.

**Review by txyyss — APPROVED** [review]
I have tested via `make atomics`. It works smoothly.

**Comment by andrew-appel** [comment]
I have moved a lot of stuff out of concurrency/conclib_{coqlib,sublist,veric}.v into other places in msl,zlist,floyd.
**At this point, once the CI completes successfully on the most recent commit, I am ready to merge it into master.**

However, there is still other stuff within concurrency/conclib_{coqlib,sublist,veric}.v  that could perhaps be of
more general interest; maybe someone should figure out where some of that stuff could go.
There are also some deprecated lemmas in conclib_sublist.v, marked with the comment "should use ... instead".
It would be nice to adapt all the clients to use different lemmas, and then delete thos.

**Pull request merged**
